=== bjoyroy/matsim-libs/contribs/carsharing/src/main/resources/dtd/vehicle_types.dtd
<?xml version="1.0" encoding="utf-8"?>

<!-- $Id$ -->

<!-- ============================================================ -->
<!ELEMENT vehicleTypes          (vehicleType*)>
<!ATTLIST vehicleTypes
          reference_layer  CDATA #IMPLIED
          xml:lang       NMTOKEN "de-CH">


<!ELEMENT vehicleType       (maxVelocity, pcuEquivalent, length, width, capacity)>

<!ATTLIST vehicleType
          name         CDATA   #REQUIRED>
          
<!ELEMENT maxVelocity (#PCDATA)>
<!ELEMENT pcuEquivalent (#PCDATA)>
<!ELEMENT length (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT capacity (#PCDATA)>

=== bjoyroy/matsim-libs/contribs/carsharing/test/input/org/matsim/contrib/carsharing/runExample/RunCarsharingIT/vehicle_types.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vehicleTypes SYSTEM "src/main/resources/dtd/vehicle_types.dtd">
<vehicleTypes>
	<vehicleType name="scooter">
			<maxVelocity>9.0</maxVelocity>
			<pcuEquivalent>0.20</pcuEquivalent>
			<length>1.15824</length>
			<width>0.3048</width>
			<capacity>2</capacity>
	</vehicleType>
	
	
	<vehicleType name="taxii">
			<maxVelocity>8.0</maxVelocity>
			<pcuEquivalent>0.20</pcuEquivalent>
			<length>1.15824</length>
			<width>0.3048</width>
			<capacity>2</capacity>
	</vehicleType>
	
	<!--
	<vehicleType name="twoway">
			<maxVelocity>9.0</maxVelocity>
			<pcuEquivalent>0.20</pcuEquivalent>
			<length>1.15824</length>
			<width>0.3048</width>
			<capacity>2</capacity>
	</vehicleType>
	-->
</vehicleTypes>
